# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.ku.com:
  peer1.ku.com:
  
networks:
  test:
    name: first-network

services:
  peer0.ku.com:

    container_name: peer0.ku.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=first-network

      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ku.com.com
      - CORE_PEER_ADDRESS=peer0.ku.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ku.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ku.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ku.com:11051
      - CORE_PEER_LOCALMSPID=kuMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/ku.com/peers/peer0.ku.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ku.com/peers/peer0.ku.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ku.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - test
  peer1.ku.com:
    container_name: peer1.ku.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=first-network

      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.ku.com
      - CORE_PEER_ADDRESS=peer1.ku.com:11055
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11055
      - CORE_PEER_CHAINCODEADDRESS=peer1.ku.com:11056
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11056
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ku.com:11055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ku.com:11055
      - CORE_PEER_LOCALMSPID=kuMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/ku.com/peers/peer1.ku.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ku.com/peers/peer1.ku.com/tls:/etc/hyperledger/fabric/tls
        - peer1.ku.com/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11055:11055
    networks:
      - test
  