# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &ku
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: kuMSP

        # ID to load the MSP definition as
        ID: kuMSP

        MSPDir: ../organizations/peerOrganizations/ku.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('kuMSP.admin', 'kuMSP.peer', 'kuMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('kuMSP.admin', 'kuMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('kuMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('kuMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.ku.com
              Port: 11051
